version: '3.8'

services:

  db:
    image: postgres:15
    container_name: business_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: businessdatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: business_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/businessdatabase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

volumes:
  20:
