version: '3.8'

services:
  db:
    image: postgres:15
    container_name: business_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: businessdatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
